AWSTemplateFormatVersion: "2010-09-09"
Description: "(SO0042) - aws-content-analysis %%VERSION%%. This is the base AWS CloudFormation template that provisions resources for the AWS Content Analysis solution."

Parameters:
  AdminEmail:
    Description: Email address of the Content Analysis Administrator
    Type: String
  ElasticSearchNodeSize:
    Description: "The node type to be provisioned for the Elasticsearch cluster"
    Type: String
    Default: "t3.small.elasticsearch"
    AllowedValues:
      - "t3.small.elasticsearch"
      - "m4.large.elasticsearch"
      - "m4.xlarge.elasticsearch"
      - "c4.large.elasticsearch"
      - "c4.xlarge.elasticsearch"
      - "r4.large.elasticsearch"
      - "r4.xlarge.elasticsearch"

Conditions:
  EnableAnonymousData: !Equals [ !FindInMap [AnonymousData,SendAnonymousData,Data], Yes]

Mappings:
  MediaInsightsEngine:
    Release:
      Version: "v1.0.0"
  ContentAnalysisApp:
    SourceCode:
      GlobalS3Bucket: "%%GLOBAL_BUCKET_NAME%%"
      TemplateKeyPrefix: "aws-content-analysis/%%VERSION%%"
      RegionalS3Bucket: "%%REGIONAL_BUCKET_NAME%%"
      CodeKeyPrefix: "aws-content-analysis/%%VERSION%%"
      Version: "%%VERSION%%"
  AnonymousData:
    SendAnonymousData:
      Data: Yes

Resources:
  # Deploy MIE Framework

  MieStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://solutions-test-reference.s3.amazonaws.com/aws-media-insights-engine/"
          - !FindInMap
            - MediaInsightsEngine
            - Release
            - Version
          - "/media-insights-stack.template"
      Parameters:
        DeployAnalyticsPipeline: Yes
        DeployTestResources: No
        MaxConcurrentWorkflows: 5
        EnableXrayTrace: Yes
        SendAnonymousData: !FindInMap [AnonymousData,SendAnonymousData,Data]
        SolutionId: SO0042

  # Deploy Elasticsearch

  ContentAnalysisElasticsearchStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - GlobalS3Bucket
          - ".s3.amazonaws.com/"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - TemplateKeyPrefix
          - "/aws-content-analysis-elasticsearch.template"
      Parameters:
        AnalyticsStreamArn: !GetAtt MieStack.Outputs.AnalyticsStreamArn
        MieDataplaneBucket: !GetAtt MieStack.Outputs.DataplaneBucket
        NodeType: !Ref ElasticSearchNodeSize

  # Deploy Auth stack

  ContentAnalysisAuthStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - GlobalS3Bucket
          - ".s3.amazonaws.com/"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - TemplateKeyPrefix
          - "/aws-content-analysis-auth.template"
      Parameters:
        AdminEmail: !Ref AdminEmail
        WorkflowApiId: !GetAtt MieStack.Outputs.WorkflowApiRestID
        DataplaneApiId: !GetAtt MieStack.Outputs.DataplaneApiRestID
        ElasticDomainArn: !GetAtt ContentAnalysisElasticsearchStack.Outputs.DomainArn
        DataplaneBucket: !GetAtt MieStack.Outputs.DataplaneBucket
        ParentStackName: !Ref MieStack

  ContentAnalysisWebStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - GlobalS3Bucket
          - ".s3.amazonaws.com/"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - TemplateKeyPrefix
          - "/aws-content-analysis-web.template"
      Parameters:
        DataplaneEndpoint: !GetAtt MieStack.Outputs.DataplaneApiEndpoint
        WorkflowEndpoint: !GetAtt MieStack.Outputs.WorkflowApiEndpoint
        ElasticEndpoint: !GetAtt ContentAnalysisElasticsearchStack.Outputs.ElasticEndpoint
        DataplaneBucket: !GetAtt MieStack.Outputs.DataplaneBucket
        UserPoolId: !GetAtt ContentAnalysisAuthStack.Outputs.UserPoolId
        IdentityPoolId: !GetAtt ContentAnalysisAuthStack.Outputs.IdentityPoolId
        PoolClientId: !GetAtt ContentAnalysisAuthStack.Outputs.UserPoolClientId

  # Deploy video workflow

  CompleteVideoWorkflow:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - GlobalS3Bucket
          - ".s3.amazonaws.com/"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - TemplateKeyPrefix
          - "/aws-content-analysis-video-workflow.template"
      Parameters:
        WorkflowCustomResourceArn:
          Fn::GetAtt:
            - MieStack
            - Outputs.WorkflowCustomResourceArn
        OperatorLibraryStack:
          Fn::GetAtt:
            - MieStack
            - Outputs.OperatorLibraryStack

  # Deploy image workflow

  CompleteImageWorkflow:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - GlobalS3Bucket
          - ".s3.amazonaws.com/"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - TemplateKeyPrefix
          - "/aws-content-analysis-image-workflow.template"
      Parameters:
        WorkflowCustomResourceArn:
          Fn::GetAtt:
            - MieStack
            - Outputs.WorkflowCustomResourceArn
        OperatorLibraryStack:
          Fn::GetAtt:
            - MieStack
            - Outputs.OperatorLibraryStack

  AnonymousDataCustomResourceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        -
          PolicyName: !Sub "${AWS::StackName}-anonymous-data-logger"
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Join ["", ["arn:aws:logs:", Ref: "AWS::Region", ":", Ref: "AWS::AccountId", ":log-group:/aws/lambda/*"]]
              -
                Effect: Allow
                Action:
                  - ssm:PutParameter
                Resource:
                  - !Join ["", ["arn:aws:ssm:", Ref: "AWS::Region", ":", Ref: "AWS::AccountId", ":parameter/*"]]

  AnonymousDataCustomResource:
    Type: AWS::Lambda::Function
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W89
            reason: "This Lambda function does not need to access any resource provisioned within a VPC."
          - id: W92
            reason: "This function does not require performance optimization, so the default concurrency limits suffice."
    Properties:
      FunctionName: !Sub ${AWS::StackName}-anonymous-data
      Description: Used to send anonymous data
      Handler: anonymous-data-logger.handler
      Role: !GetAtt AnonymousDataCustomResourceRole.Arn
      Code:
        S3Bucket: !Join [ "-", [ !FindInMap [ "ContentAnalysisApp", "SourceCode", "RegionalS3Bucket" ], Ref: "AWS::Region" ] ]
        S3Key: !Join [ "/", [ !FindInMap [ "ContentAnalysisApp", "SourceCode", "CodeKeyPrefix" ], "anonymous-data-logger.zip" ] ]
      Runtime:  python3.8
      Timeout: 180

  # SendAnonymousData
  AnonymousDataUuid:
    Condition: EnableAnonymousData
    Type: "Custom::UUID"
    Properties:
      ServiceToken: !GetAtt AnonymousDataCustomResource.Arn
      Resource: UUID

  AnonymousMetric:
    Condition: EnableAnonymousData
    Type: "Custom::AnonymousMetric"
    Properties:
      ServiceToken: !GetAtt AnonymousDataCustomResource.Arn
      Resource: AnonymousMetric
      SolutionId: "SO0042"
      UUID: !GetAtt AnonymousDataUuid.UUID
      Version: !FindInMap ["ContentAnalysisApp", "SourceCode", "Version"]

Outputs:
  ContentAnalyisSolution:
    Value: !GetAtt ContentAnalysisWebStack.Outputs.CloudfrontUrl
